[project]
name = "study-langgraph"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "langchain>=0.3.23",
    "langgraph>=0.3.31",
    "openai>=1.75.0",
]
